-- 初始化数据库
CREATE DATABASE IF NOT EXISTS uni_admin CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 创建基础表结构（后续由 Prisma 管理）
-- CREATE TABLE IF NOT EXISTS users (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   username VARCHAR(50) NOT NULL UNIQUE,
--   email VARCHAR(100) NOT NULL UNIQUE,
--   nickname VARCHAR(50),
--   password_hash VARCHAR(255) NOT NULL,
--   status ENUM('ACTIVE', 'INACTIVE', 'LOCKED') DEFAULT 'ACTIVE',
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );
